name: data-factory-deploy
description: Deploy Azure Data Factory resources

inputs:
  resourceGroupName:
    description: 'Data Factory resource group name'
    required: true
  dataFactoryName:
    description: 'Data factory name'
    required: true
  armTemplateFile:
    description: 'ARM template file name'
    required: false
    default: './ARMTemplateForFactory.json'
  armTemplateParametersFile:
    description: 'ARM template parameters file name'
    required: false
    default: './ARMTemplateParametersForFactory.json'
  additionalParameters:
    description: 'Parameters which will be replaced in the ARM template'
    required: false
    default: ''
  skipAzModuleInstallation:
    description: 'Parameters which skip the Az module installation'
    required: false
    default: 'false'
  deleteDeployment:
    description: 'Whether to delete the deployment after deploying'
    required: false
    default: 'true'
  useLinkedTemplates:
    description: 'Whether to use linked templates for ARM deployment'
    required: false
    default: 'false'
  armLinkedTemplateFile:
    description: 'ARM linked template file name'
    required: false
    default: './linkedTemplates/ArmTemplate_master.json'

runs:
  using: 'composite'
  steps:
    - name: Set deploymentTemplate value
      id: variables
      shell: bash
      run: |
        echo "deploymentName=deployment-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
        if [ ${{ inputs.useLinkedTemplates }} == 'true' ]; then
          echo "Use Linked ARM Templates"
          echo "deploymentTemplate=${{ inputs.armLinkedTemplateFile }}" >> $GITHUB_ENV
        else
          echo "Use Default ARM Template"
          echo "deploymentTemplate=${{ inputs.armTemplateFile }}" >> $GITHUB_ENV
        fi

    - name: Install Az PowerShell module
      run: if('${{ inputs.skipAzModuleInstallation }}' -ne 'true') { Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force }
      shell: pwsh

    - name: Run Pre-deployment script
      run: |
        ${{ github.action_path }}/PrePostDeploymentScript.Ver2.ps1 `
          -ArmTemplate "${{ inputs.armTemplateFile }}" `
          -ResourceGroupName "${{ inputs.resourceGroupName }}" `
          -DataFactoryName "${{ inputs.dataFactoryName }}" `
          -Predeployment $true `
          -DeleteDeployment $false
      shell: pwsh

    - name: Run ARM deploy
      #uses: azure/arm-deploy@v1
      uses: fredgohsman/arm-deploy@debug
      with:
        resourceGroupName: ${{ inputs.resourceGroupName }}
        template: ${{ steps.variables.outputs.deploymentTemplate }}
        parameters: ${{ inputs.armTemplateParametersFile }} factoryName=${{ inputs.dataFactoryName }} ${{ inputs.additionalParameters }}
        deploymentName: ${{ steps.variables.outputs.deploymentName }}
        
    - name: Run Post-deployment script
      run: |
        ${{ github.action_path }}/PrePostDeploymentScript.Ver2.ps1 `
          -armTemplate "${{ inputs.armTemplateFile }}" `
          -ResourceGroupName "${{ inputs.resourceGroupName }}" `
          -DataFactoryName '${{ inputs.dataFactoryName }}' `
          -predeployment $false `
          -deleteDeployment $${{ inputs.deleteDeployment }}
      shell: pwsh
